# Generated by Django 4.2.3 on 2023-08-11 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department'),
        ),
        migrations.AddField(
            model_name='notification',
            name='branch',
            field=models.ManyToManyField(to='academics.branch'),
        ),
        migrations.AddField(
            model_name='notification',
            name='course',
            field=models.ManyToManyField(to='academics.course'),
        ),
        migrations.AddField(
            model_name='notification',
            name='dept',
            field=models.ManyToManyField(to='academics.department'),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.branch'),
        ),
    ]
